# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


    runs-on: ubuntu-latest


      -name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5.8
      with:
        image: hassamkhan123/cicdrepo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         

