jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
       os: [ubuntu-latest, windows-latest, macOS-latest]
  build-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8.0
      uses: actions/setup-java@v3
      with:
        java-version: 8.0
 

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build and Push docker image

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: hassamkhan123/cicdrepo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}   
        password: ${{ secrets.DOCKER_PASSWORD }}
